export const cities = [
  {
    name_ar: "الرياض",
    name_en: "Riyadh",
    neighborhoods: [
      { name_ar: "العليا", name_en: "Olaya" },
      { name_ar: "الملز", name_en: "Al-Malaz" },
      { name_ar: "الروضة", name_en: "Al-Rawdah" },
      { name_ar: "النخيل", name_en: "Al-Nakheel" },
      { name_ar: "العود", name_en: "Al-Oud" },
    ],
    img_url: "17.jpg",
  },
  {
    name_ar: "جدة",
    name_en: "Jeddah",
    neighborhoods: [
      { name_ar: "البلد", name_en: "Al-Balad" },
      { name_ar: "الحمراء", name_en: "Al-Hamra" },
      { name_ar: "النزهة", name_en: "Al-Nuzha" },
      { name_ar: "السلامة", name_en: "Al-Salamah" },
      { name_ar: "الشاطئ", name_en: "Al-Shati" },
    ],
    img_url: "1.jpg",
  },
  {
    name_ar: "الدمام",
    name_en: "Dammam",
    neighborhoods: [
      { name_ar: "العدامة", name_en: "Al-Adama" },
      { name_ar: "السويدي", name_en: "Al-Suwaidi" },
      { name_ar: "الشاطئ", name_en: "Al-Shati" },
      { name_ar: "النهضة", name_en: "An Nahdah" },
      { name_ar: "الواحة", name_en: "Al-Waha" },
    ],
    img_url: "2.jpg",
  },
  {
    name_ar: "مكة المكرمة",
    name_en: "Makkah",
    neighborhoods: [
      { name_ar: "الحرم", name_en: "Al-Haram" },
      { name_ar: "العزيزية", name_en: "Al-Aziziyah" },
      { name_ar: "المنصورية", name_en: "Al-Mansour" },
      { name_ar: "الشيشة", name_en: "Al-Shisha" },
      { name_ar: "النزهة", name_en: "Al-Nuzhah" },
    ],
    img_url: "3.jpg",
  },
  {
    name_ar: "المدينة المنورة",
    name_en: "Madinah",
    neighborhoods: [
      { name_ar: "النور", name_en: "Al-Noor" },
      { name_ar: "الهجرة", name_en: "Al-Hijrah" },
      { name_ar: "السلام", name_en: "Al-Salaam" },
      { name_ar: "الفارس", name_en: "Al-Faris" },
      { name_ar: "جنوب المدينة", name_en: "Al-Madinah South" },
    ],
    img_url: "4.jpg",
  },
  {
    name_ar: "الخبر",
    name_en: "Khobar",
    neighborhoods: [
      { name_ar: "العليا", name_en: "Al-Ulaya" },
      { name_ar: "الثقبة", name_en: "Thuqbah" },
      { name_ar: "الكورنيش", name_en: "Corniche" },
      { name_ar: "اليرموك", name_en: "Al-Yarmouk" },
      { name_ar: "التميمي", name_en: "Al-Tamimi" },
    ],
    img_url: "4.jpg",
  },
  {
    name_ar: "القصيم",
    name_en: "Al-Qassim",
    neighborhoods: [],
    img_url: "5.jpg",
  },
  {
    name_ar: "الإحساء",
    name_en: "Al-Ahsa",
    neighborhoods: [],
    img_url: "6.jpg",
  },
  {
    name_ar: "حائل",
    name_en: "Hail",
    neighborhoods: [],
    img_url: "7.jpg",
  },
  {
    name_ar: "تبوك",
    name_en: "Tabuk",
    neighborhoods: [],
    img_url: "8.jpg",
  },
  {
    name_ar: "الطائف",
    name_en: "Taif",
    neighborhoods: [],
    img_url: "9.jpg",
  },
  {
    name_ar: "ابها",
    name_en: "Abha",
    neighborhoods: [],
    img_url: "10.jpg",
  },
  {
    name_ar: "الباحة",
    name_en: "Al-Baha",
    neighborhoods: [],
    img_url: "11.jpg",
  },
  {
    name_ar: "عرعر",
    name_en: "Arar",
    neighborhoods: [],
    img_url: "12.jpg",
  },
  {
    name_ar: "نجران",
    name_en: "Najran",
    neighborhoods: [],
    img_url: "13.jpg",
  },
  {
    name_ar: "جازان",
    name_en: "Jazan",
    neighborhoods: [],
    img_url: "14.jpg",
  },
  {
    name_ar: "عسير",
    name_en: "Asir",
    neighborhoods: [],
    img_url: "15.jpg",
  },
  {
    name_ar: "الجوف",
    name_en: "Al-Jouf",
    neighborhoods: [],
    img_url: "16.jpg",
  },
];
